/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.8.1
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as HelloBaseSvc from "./HelloBaseSvc";
export { HelloBaseSvc as HelloBaseSvc };
import * as HelloSvc from "./HelloSvc";
export { HelloSvc as HelloSvc };
